### ISSUE TITLE
soot class path问题

### ISSUE THREAD

**Issue by FlyingOnion** [HelloKittyNII/soot-android-static-analysis#1]
您好，我用您的代码跑了app-debug，很顺利，但跑一些其他apk时都出现了soot class path设置的问题
比如Wifi共享大师会出现这个`couldn't find class: com.wifi.connect.e.u (is your soot-class-path set properly?)`
请问您是怎么解决的？

**Comment by HelloKittyNII** [comment]
> 您好，我用您的代码跑了app-debug，很顺利，但跑一些其他apk时都出现了soot class path设置的问题
> 比如Wifi共享大师会出现这个`couldn't find class: com.wifi.connect.e.u (is your soot-class-path set properly?)`
> 请问您是怎么解决的？

是跑哪个测试类的时候，出现问题呢？

**Comment by FlyingOnion** [comment]
> > 您好，我用您的代码跑了app-debug，很顺利，但跑一些其他apk时都出现了soot class path设置的问题
> > 比如Wifi共享大师会出现这个`couldn't find class: com.wifi.connect.e.u (is your soot-class-path set properly?)`
> > 请问您是怎么解决的？
> 
> 是跑哪个测试类的时候，出现问题呢？

在`EmailSootChecker`, `UrlSootChecker`, `ZipVulnChecker`中会出现，我刚刚试过用dex2jar将反编译的jar文件路径添加进去就不报这个错了，代码加一句 `pathList.add("libs/classes-dex2jar.jar");`就行
这样做有点麻烦，而且程序报了其他错，现在还在想办法

**Comment by FlyingOnion** [comment]
我大概知道问题出在哪了，class path里面的类，必须覆盖apk中所有的类，包括import的第三方包中的类。app-debug.apk里面的依赖项都用gradle安装完了，而其他一些apk有第三方包，gradle或maven没办法安装的，就会报这个错

**Comment by FlyingOnion** [comment]
问题解决了，加一句`Options.v().set_allow_phantom_refs(true)`就可以了
另外这个库有时会出现NPE，建议升级到最新的2.6版本
